### PR TITLE
TASK-71389: Introduce crowdin wf using v2 api

### PR DESCRIPTION
**Pull request by bourasom**
This PR aims to introduce new github action wf based on crowdin v2 API

### CODE REVIEW

**Review by boubaker — COMMENTED** [review]
There is a missing bundle file https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-sites-extension/src/main/resources/locale/portlet/Portlets_en.properties

**Comment by boubaker** [comment]
List of available `_en.properties` files can be found using this search input BTW
image

**Review by hbenali — DISMISSED** [review]

**Comment by bourasom** [comment]
> There is a missing bundle file https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-sites-extension/src/main/resources/locale/portlet/Portlets_en.properties

My changes were based on the actual translation.properties. After the process is set, it is possible for you in product side to add the missing entries. The idea was to keep the existant behavior

**Comment by boubaker** [comment]
> > There is a missing bundle file https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-sites-extension/src/main/resources/locale/portlet/Portlets_en.properties
> 
> My changes were based on the actual translation.properties. After the process is set, it is possible for you in product side to add the missing entries. The idea was to keep the existant behavior

ok, I see your point, but there [is already a PR](url) on develop to add it in `translation.properties` https://github.com/Meeds-io/meeds/pull/2026/files#diff-b4b549e33289f0167520d66382c0de4fc1901698dfe8dc8eb3910081ffc0412aR30

Can you please add it to not forget it (two parallel PRs)

**Review by hbenali — APPROVED** [review]

**Review by boubaker — APPROVED** [review]

**Pull request merged**
